theme: jekyll-theme-cayman
title: "XFDetector: \n Cross-Failure Bug Detection in Persistent Memory Programs"
name: "XFDetector: \n Cross-Failure Bug Detection in Persistent Memory Programs"
show_downloads: true
description: 
